/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\hrk\\Desktop\\rooon-k\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-17c76c92",
    path: "/docs/Markdown%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17c76c92").then(next)
    },
  },
  {
    path: "/docs/Markdown学习记录.html",
    redirect: "/docs/Markdown%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: "/docs/Markdown学习记录.html",
    redirect: "/docs/Markdown%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html"
  },
  {
    name: "v-c26aca7e",
    path: "/docs/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c26aca7e").then(next)
    },
  },
  {
    name: "v-80398af6",
    path: "/docs/typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-80398af6").then(next)
    },
  },
  {
    name: "v-c75b6036",
    path: "/docs/nodejsFs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c75b6036").then(next)
    },
  },
  {
    name: "v-30cac9f4",
    path: "/docs/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2web%E6%9C%8D%E5%8A%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30cac9f4").then(next)
    },
  },
  {
    path: "/docs/从零开始部署web服务.html",
    redirect: "/docs/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2web%E6%9C%8D%E5%8A%A1.html"
  },
  {
    path: "/docs/从零开始部署web服务.html",
    redirect: "/docs/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2web%E6%9C%8D%E5%8A%A1.html"
  },
  {
    name: "v-cc39e2f6",
    path: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc39e2f6").then(next)
    },
  },
  {
    path: "/docs/网站组组会1.html",
    redirect: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A1.html"
  },
  {
    path: "/docs/网站组组会1.html",
    redirect: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A1.html"
  },
  {
    name: "v-560d87a5",
    path: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-560d87a5").then(next)
    },
  },
  {
    path: "/docs/网站组组会2.html",
    redirect: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A2.html"
  },
  {
    path: "/docs/网站组组会2.html",
    redirect: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A2.html"
  },
  {
    name: "v-123800c5",
    path: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-123800c5").then(next)
    },
  },
  {
    path: "/docs/网站组组会3.html",
    redirect: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A3.html"
  },
  {
    path: "/docs/网站组组会3.html",
    redirect: "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A3.html"
  },
  {
    name: "v-f780889e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f780889e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-59ff4596",
    path: "/tag/Markdown/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-59ff4596").then(next)
    },
    meta: {"pid":"tags","id":"Markdown"}
  },
  {
    path: "/tag/Markdown/index.html",
    redirect: "/tag/Markdown/"
  },
  {
    name: "v-e8d86dc8",
    path: "/tag/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d86dc8").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tag/js/index.html",
    redirect: "/tag/js/"
  },
  {
    name: "v-6bf1c8da",
    path: "/tag/nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6bf1c8da").then(next)
    },
    meta: {"pid":"tags","id":"nodejs"}
  },
  {
    path: "/tag/nodejs/index.html",
    redirect: "/tag/nodejs/"
  },
  {
    name: "v-e14f25f6",
    path: "/tag/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e14f25f6").then(next)
    },
    meta: {"pid":"tags","id":"Linux"}
  },
  {
    path: "/tag/Linux/index.html",
    redirect: "/tag/Linux/"
  },
  {
    name: "v-4ba8f3c6",
    path: "/tag/组会/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4ba8f3c6").then(next)
    },
    meta: {"pid":"tags","id":"组会"}
  },
  {
    path: "/tag/组会/index.html",
    redirect: "/tag/组会/"
  },
  {
    name: "v-65506e4c",
    path: "/categories/学习笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-65506e4c").then(next)
    },
    meta: {"pid":"categories","id":"学习笔记"}
  },
  {
    path: "/categories/学习笔记/index.html",
    redirect: "/categories/学习笔记/"
  },
  {
    name: "v-95f08732",
    path: "/categories/项目实战/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-95f08732").then(next)
    },
    meta: {"pid":"categories","id":"项目实战"}
  },
  {
    path: "/categories/项目实战/index.html",
    redirect: "/categories/项目实战/"
  },
  {
    name: "v-5166e303",
    path: "/categories/网站组/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5166e303").then(next)
    },
    meta: {"pid":"categories","id":"网站组"}
  },
  {
    path: "/categories/网站组/index.html",
    redirect: "/categories/网站组/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]