/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Rooon-K",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "markdown学习记录",
      "frontmatter": {
        "title": "markdown学习记录",
        "tags": [
          "Markdown"
        ],
        "categories": [
          "学习笔记"
        ],
        "date": "2022-11-19T00:00:00.000Z"
      },
      "regularPath": "/docs/Markdown%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html",
      "relativePath": "docs/Markdown学习记录.md",
      "key": "v-17c76c92",
      "path": "/docs/Markdown%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html"
    },
    {
      "title": "vuepress-theme-reco",
      "frontmatter": {
        "title": "vuepress-theme-reco",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/docs/guide.html",
      "relativePath": "docs/guide.md",
      "key": "v-c26aca7e",
      "path": "/docs/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ]
    },
    {
      "title": "TypeScript学习手册",
      "frontmatter": {
        "title": "TypeScript学习手册",
        "tags": [
          "js"
        ],
        "categories": [
          "学习笔记"
        ],
        "date": "2023-2-3"
      },
      "regularPath": "/docs/typescript.html",
      "relativePath": "docs/typescript.md",
      "key": "v-80398af6",
      "path": "/docs/typescript.html",
      "headers": [
        {
          "level": 2,
          "title": "基础类型",
          "slug": "基础类型"
        },
        {
          "level": 2,
          "title": "变量声明",
          "slug": "变量声明"
        },
        {
          "level": 2,
          "title": "接口",
          "slug": "接口"
        },
        {
          "level": 2,
          "title": "类",
          "slug": "类"
        },
        {
          "level": 2,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 2,
          "title": "泛型",
          "slug": "泛型"
        },
        {
          "level": 2,
          "title": "枚举",
          "slug": "枚举"
        },
        {
          "level": 2,
          "title": "类型推论",
          "slug": "类型推论"
        },
        {
          "level": 2,
          "title": "类型兼容性",
          "slug": "类型兼容性"
        },
        {
          "level": 2,
          "title": "高级类型",
          "slug": "高级类型"
        },
        {
          "level": 2,
          "title": "Symbols",
          "slug": "symbols"
        }
      ]
    },
    {
      "title": "nodejs fs",
      "frontmatter": {
        "title": "nodejs fs",
        "tags": [
          "nodejs"
        ],
        "categories": [
          "学习笔记"
        ],
        "date": "2022-11-18T00:00:00.000Z"
      },
      "regularPath": "/docs/nodejsFs.html",
      "relativePath": "docs/nodejsFs.md",
      "key": "v-c75b6036",
      "path": "/docs/nodejsFs.html"
    },
    {
      "title": "从零开始部署web服务",
      "frontmatter": {
        "title": "从零开始部署web服务",
        "tags": [
          "Linux"
        ],
        "categories": [
          "项目实战"
        ],
        "date": "2023-3-23"
      },
      "regularPath": "/docs/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2web%E6%9C%8D%E5%8A%A1.html",
      "relativePath": "docs/从零开始部署web服务.md",
      "key": "v-30cac9f4",
      "path": "/docs/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2web%E6%9C%8D%E5%8A%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "一、环境需求",
          "slug": "一、环境需求"
        },
        {
          "level": 2,
          "title": "二、部署过程",
          "slug": "二、部署过程"
        },
        {
          "level": 3,
          "title": "1. vim缺失 报错bash vim: command not found",
          "slug": "_1-vim缺失-报错bash-vim-command-not-found"
        },
        {
          "level": 3,
          "title": "2. NVM安装",
          "slug": "_2-nvm安装"
        },
        {
          "level": 3,
          "title": "3. nvm的使用——nodejs版本控制",
          "slug": "_3-nvm的使用-nodejs版本控制"
        },
        {
          "level": 3,
          "title": "4. 安装gcc",
          "slug": "_4-安装gcc"
        },
        {
          "level": 3,
          "title": "5. 安装nginx",
          "slug": "_5-安装nginx"
        },
        {
          "level": 3,
          "title": "6. 配置nginx",
          "slug": "_6-配置nginx"
        }
      ]
    },
    {
      "title": "网站组组会0312",
      "frontmatter": {
        "title": "网站组组会0312",
        "tags": [
          "组会"
        ],
        "categories": [
          "网站组"
        ],
        "date": "2023-3-12"
      },
      "regularPath": "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A1.html",
      "relativePath": "docs/网站组组会1.md",
      "key": "v-cc39e2f6",
      "path": "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A1.html",
      "headers": [
        {
          "level": 2,
          "title": "自我介绍",
          "slug": "自我介绍"
        },
        {
          "level": 2,
          "title": "什么是前端",
          "slug": "什么是前端"
        },
        {
          "level": 2,
          "title": "前端的学习路线",
          "slug": "前端的学习路线"
        },
        {
          "level": 2,
          "title": "我是怎么学习前端的",
          "slug": "我是怎么学习前端的"
        },
        {
          "level": 2,
          "title": "大家学前端想做一些什么东西",
          "slug": "大家学前端想做一些什么东西"
        }
      ]
    },
    {
      "title": "网站组组会之了解HTML",
      "frontmatter": {
        "title": "网站组组会之了解HTML",
        "tags": [
          "组会"
        ],
        "categories": [
          "网站组"
        ],
        "date": "2023-3-19"
      },
      "regularPath": "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A2.html",
      "relativePath": "docs/网站组组会2.md",
      "key": "v-560d87a5",
      "path": "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A2.html",
      "headers": [
        {
          "level": 2,
          "title": "一、初识HTML",
          "slug": "一、初识html"
        },
        {
          "level": 3,
          "title": "1.概念",
          "slug": "_1-概念"
        },
        {
          "level": 3,
          "title": "2.基础结构",
          "slug": "_2-基础结构"
        },
        {
          "level": 3,
          "title": "3.元素组成",
          "slug": "_3-元素组成"
        },
        {
          "level": 3,
          "title": "4.嵌套元素",
          "slug": "_4-嵌套元素"
        },
        {
          "level": 3,
          "title": "5.空元素",
          "slug": "_5-空元素"
        },
        {
          "level": 2,
          "title": "二、行内元素",
          "slug": "二、行内元素"
        },
        {
          "level": 3,
          "title": "1. <span>",
          "slug": "_1-span"
        },
        {
          "level": 3,
          "title": "2. <code>",
          "slug": "_2-code"
        },
        {
          "level": 3,
          "title": "3. 斜体<em>",
          "slug": "_3-斜体-em"
        },
        {
          "level": 3,
          "title": "4. 强调<strong>",
          "slug": "_4-强调-strong"
        },
        {
          "level": 3,
          "title": "5. 超链接<a>",
          "slug": "_5-超链接-a"
        },
        {
          "level": 2,
          "title": "三、块级元素",
          "slug": "三、块级元素"
        },
        {
          "level": 3,
          "title": "1. <p>",
          "slug": "_1-p"
        },
        {
          "level": 3,
          "title": "2. <h>",
          "slug": "_2-h"
        },
        {
          "level": 3,
          "title": "3. <ul>",
          "slug": "_3-ul"
        },
        {
          "level": 3,
          "title": "4. <ol>",
          "slug": "_4-ol"
        },
        {
          "level": 3,
          "title": "5. <div>",
          "slug": "_5-div"
        },
        {
          "level": 2,
          "title": "四、行内块元素",
          "slug": "四、行内块元素"
        },
        {
          "level": 3,
          "title": "1. <img>",
          "slug": "_1-img"
        },
        {
          "level": 3,
          "title": "2. <input>",
          "slug": "_2-input"
        },
        {
          "level": 3,
          "title": "3. <select>、<option>",
          "slug": "_3-select-、-option"
        },
        {
          "level": 2,
          "title": "作业",
          "slug": "作业"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    },
    {
      "title": "网站组组会之了解CSS(一)",
      "frontmatter": {
        "title": "网站组组会之了解CSS(一)",
        "tags": [
          "组会"
        ],
        "categories": [
          "网站组"
        ],
        "date": "2023-3-19"
      },
      "regularPath": "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A3.html",
      "relativePath": "docs/网站组组会3.md",
      "key": "v-123800c5",
      "path": "/docs/%E7%BD%91%E7%AB%99%E7%BB%84%E7%BB%84%E4%BC%9A3.html",
      "headers": [
        {
          "level": 2,
          "title": "一、初识CSS",
          "slug": "一、初识css"
        },
        {
          "level": 3,
          "title": "1.概念",
          "slug": "_1-概念"
        },
        {
          "level": 3,
          "title": "2.使用CSS",
          "slug": "_2-使用css"
        },
        {
          "level": 3,
          "title": "3.基础结构",
          "slug": "_3-基础结构"
        },
        {
          "level": 2,
          "title": "二、选择器",
          "slug": "二、选择器"
        },
        {
          "level": 3,
          "title": "1.类型(元素)选择器",
          "slug": "_1-类型-元素-选择器"
        },
        {
          "level": 3,
          "title": "2.类选择器",
          "slug": "_2-类选择器"
        },
        {
          "level": 3,
          "title": "3.id选择器",
          "slug": "_3-id选择器"
        },
        {
          "level": 3,
          "title": "4.伪类选择器",
          "slug": "_4-伪类选择器"
        },
        {
          "level": 3,
          "title": "5.标签属性选择器",
          "slug": "_5-标签属性选择器"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "欢迎来到Rooon-K的博客",
        "tagline": "在这分享一些学习笔记&心得",
        "bgImageStyle": {
          "height": "100"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-f780889e",
      "path": "/"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Markdown Tags"
      },
      "regularPath": "/tag/Markdown/",
      "key": "v-59ff4596",
      "path": "/tag/Markdown/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "nodejs Tags"
      },
      "regularPath": "/tag/nodejs/",
      "key": "v-6bf1c8da",
      "path": "/tag/nodejs/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Linux Tags"
      },
      "regularPath": "/tag/Linux/",
      "key": "v-e14f25f6",
      "path": "/tag/Linux/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "组会 Tags"
      },
      "regularPath": "/tag/%E7%BB%84%E4%BC%9A/",
      "key": "v-4ba8f3c6",
      "path": "/tag/组会/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "学习笔记 Categories"
      },
      "regularPath": "/categories/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/",
      "key": "v-65506e4c",
      "path": "/categories/学习笔记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "项目实战 Categories"
      },
      "regularPath": "/categories/%E9%A1%B9%E7%9B%AE%E5%AE%9E%E6%88%98/",
      "key": "v-95f08732",
      "path": "/categories/项目实战/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "网站组 Categories"
      },
      "regularPath": "/categories/%E7%BD%91%E7%AB%99%E7%BB%84/",
      "key": "v-5166e303",
      "path": "/categories/网站组/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "文档",
        "icon": "reco-message",
        "items": [
          {
            "text": "nodeFs",
            "link": "/docs/nodejsFs"
          }
        ]
      },
      {
        "text": "联系我",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/Rooon-K",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        "",
        "theme",
        "plugin",
        "api"
      ]
    },
    "subSidebar": "auto",
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "OrangeSiteDeveloper",
        "desc": "橙果工作室",
        "logo": "https://avatars.githubusercontent.com/u/87692517?s=200&v=4",
        "link": "https://github.com/OrangeSiteDeveloper"
      },
      {
        "title": "ShawnZhou的小站",
        "desc": "我翔哥",
        "logo": "https://shawnzhou.world/images/avatar1.png",
        "link": "https://shawnzhou.world/"
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "Rooon-K",
    "authorAvatar": "/avatar.jpg",
    "startYear": "2022",
    "mode": "light",
    "modePicker": true
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}