/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Markdown",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Markdown/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/js/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "nodejs",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/nodejs/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "Linux",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Linux/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "组会",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/组会/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "学习笔记",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/学习笔记/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "项目实战",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/项目实战/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "网站组",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/网站组/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
}]